---


- name: Download marathon
  run_once: true
  delegate_to: "127.0.0.1"
  get_url:
    url: http://downloads.mesosphere.com/marathon/v1.5.1/marathon-1.5.1.tgz
    dest: "{{software_path}}"

- name: Copy to Other machine
  copy:
    src: "{{software_path}}/marathon-1.5.1.tgz"
    dest: /tmp
    mode: u=rw


- name: Unarchive marathon
  unarchive: src=/tmp/marathon-1.5.1.tgz dest=/tmp copy=yes


- name: clear marathon home dir
  command: rm -rf {{remote_dir}}/marathon


- name: Make data dir
  file:
    path: "/data/marathon/log"
    state: directory


- name: Mv all to marathon home
  command: mv -f /tmp/marathon-1.5.0-96-gf84298d {{remote_dir}}/marathon


- name: Copy marathon.sh
  copy: src=marathon.sh dest={{remote_dir}}/marathon/bin mode="u=rwx"
