---

- hosts: all
  remote_user: root
  roles:
    - install
  tags: install_denpendencies


- hosts: all
  remote_user: root
  vars:
    test: false
  roles:
    - install_mesos
  tags: install_mesos


- hosts: slave
  remote_user: root
  roles:
    - install_docker
  tags: install_docker


- hosts: master
  remote_user: root
  roles:
    - install_zk
  vars:
    dataDir: "{{remote_dir}}/zookeeper/data"
  tags: install_zk


- hosts: master
  remote_user: root
  roles:
    - install_marathon
  tags: install_marathon


- hosts: master
  remote_user: root
  vars:
    quorum: 2
    mesos_zk: zk://192.168.50.4:2181,192.168.50.5:2181,192.168.50.6:2181/mesos
    master: zk://192.168.50.4:2181,192.168.50.5:2181,192.168.50.6:2181/mesos
    marathon_zk: zk://192.168.50.4:2181,192.168.50.5:2181,192.168.50.6:2181/marathon
  roles:
    - start_master
  tags: start_master


- hosts: slave
  remote_user: root
  vars:
    master: zk://192.168.50.4:2181,192.168.50.5:2181,192.168.50.6:2181/mesos
  roles:
    - start_slave
  tags: start_slave


- hosts: master
  remote_user: root
  vars:
    marathon_zk: zk://192.168.50.4:2181,192.168.50.5:2181,192.168.50.6:2181/marathon
    master: zk://192.168.50.4:2181,192.168.50.5:2181,192.168.50.6:2181/mesos
  roles:
    - start_framework
  tags: start_framework
