---

- name: check mesos.tar.gz file
  delegate_to: "127.0.0.1"
  run_once: true
  command: ls "{{software_path}}/mesos-1.4.1.tar.gz"
  ignore_errors: true
  register: file_exist


- name: Download mesos
  run_once: true
  delegate_to: "127.0.0.1"
  get_url:
    url: http://archive.apache.org/dist/mesos/1.4.1/mesos-1.4.1.tar.gz
    dest: "{{software_path}}"
  when: file_exist['failed']


- name: Copy mesos to other machine
  copy:
    src: "{{software_path}}/mesos-1.4.1.tar.gz"
    dest: /tmp


- name: Unarchive mesos
  unarchive: src=/tmp/mesos-1.4.1.tar.gz dest=/tmp copy=yes


- name: Make build dir
  file:
    path: "/tmp/mesos-1.4.1/build"
    state: directory


- name: Configure
  command: chdir="/tmp/mesos-1.4.1" ./configure --prefix={{remote_dir}}/mesos


- name: make
  make:
    chdir: "/tmp/mesos-1.4.1"
    params:
      NUM_THREAD: 2


- name: make check
  make:
    chdir: "/tmp/mesos-1.4.1"
    target: check
  when: "{{test}}"


- name: Make install
  sudo: yes
  make:
    chdir: "/tmp/mesos-1.4.1"
    target: install


- name: make data dir
  file: path={{item}} state=directory
  with_items:
    - /data/mesos/master/log
    - /data/mesos/slave/log

- name: Copy mesos.sh
  copy: src=mesos.sh dest={{remote_dir}}/mesos/sbin mode="u=rwx"
